[allowlist]
  description = "Global Allowlist"
  paths = [
    # Ignore the security guides because these contain a lot of example secret
    # values
    '''(?:^|\/)_?guides\/security[^\/]+\.(html|adoc)$''',
  ]
